name: 'Setup Java and Ant'

on:
  workflow_call:
    inputs:
      branches:
        description: 'Branches to trigger the workflow'
        required: true
        type: string
      java-version:
        description: 'Java version to setup'
        required: true
        type: string
        default: '1.5'
      ant-version:
        description: 'Apache Ant version to install'
        required: true
        type: string
        default: '1.8.4'

jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and tar java 5 file
        run: |
          chmod +x jdk-1_5_0_22-linux-amd64.bin 
          ./jdk-1_5_0_22-linux-amd64.bin > /dev/null < <(echo yes)
          tar -czf java-package.tar.gz ./jdk1.5.0_22

      - name: Setup Java 5 using tar file
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          java-version: ${{ inputs.java-version }}
          jdkFile: ${{ github.workspace }}/java-package.tar.gz
          architecture: x64
      
      - name: Verify Java version
        run: java -version
      
      - name: Install Apache Ant
        run: |
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-${{ inputs.ant-version }}-bin.tar.gz \
          && tar -xzf ./apache-ant-${{ inputs.ant-version }}-bin.tar.gz -C /opt/ \
          && ln -s /opt/apache-ant-${{ inputs.ant-version }} /opt/ant 

      - name: Update PATH with Ant
        run: |
          echo "ANT_HOME=/opt/ant" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANT_HOME/bin" >> $GITHUB_ENV

      - name: Verify Ant version
        run: ant -version
      
      - name: Build with Ant
        run: |
          ant clean compile

      - name: Listar diretórios no diretório raiz
        run: |
          echo "Listando diretórios no diretório raiz:"
          ls -d /*/
        
          
      #- name: Teste COPY path
      #  run: |
      #    CAMINHO_TESTE="../TESTE%20UNITÁRIO/Xml"
      #    ARQUIVO=$(ls "$CAMINHO_TESTE/teste.txt")
      #    printf "Arquivo encontrado: %s\n" "$ARQUIVO"
      #    cat "$ARQUIVO"
        

        


     

      
   


